### PR TITLE
Feature/base typography styles

### PR DESCRIPTION
**Pull request by code4cake**
Hey I finished the styling of the headings, code, paragraphs, etc. 

I left all my changes in the old `lib` folder so you can take a look at the structure, and tell me if I need to change anything, etc. 

Point the `gulp` task to that old folder so you can see the changes live. So please do that so you can see it live.

### CODE REVIEW

**Review by WMontagnon — COMMENTED** [review]
Well, you've done some tremendous work there, thanks !

I think it just needs some change, not in the content which is great, but in architecture :
- First of all, I quite like the new architecture where the files are stored in the assets folder, I think it's simpler for users,
- I'd like to keep the variables, mixins and functions folders separated, with multiple files in here, just in case there is many components in the future.

Well, that's about it, what do you think ? (It's a collaborative work, don't hesitate to oppose your opinion if you disagree).

**Comment by code4cake** [comment]
That sounds good! I'll  make the changes and resubmit the PR.

PS: What do you think about adding an `.editorcofig`to the project. Something simple like this:

```
root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = tab
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false
```

**Comment by code4cake** [comment]
Hey I updated and the architecture of the project. Take a look and let me know what you think

**Review by WMontagnon — APPROVED** [review]
Really nice job you've done here, thanks so much for your input !

**Pull request merged**
